### ISSUE TITLE
How to set list bullet align to top (start)? 

### ISSUE THREAD

**Issue by steve28100** [flutter/flutter_markdown#147]
Hello, I want to set the bullet align to top like this:

![image](https://user-images.githubusercontent.com/55441199/69047763-838c3a00-0a2e-11ea-959b-a9538086c7a9.png)

I don't find any attribute to change the text align for the bullet list. It is possible?

**Comment by yuwonom** [comment]
Why is this issue closed?

**Comment by domesticmouse** [comment]
My understanding is this bug was fixed by the linked fix. Is this understanding incorrect?

**Comment by mayurdhurpate** [comment]
@domesticmouse  I feel the bullet alignment still doesn't feel right. I just added bullets for version  `flutter_markdown: ^0.3.2` and this is how it looks like:

![Screenshot_2020-02-11-23-57-40-207_com pruoo pruoo_app](https://user-images.githubusercontent.com/10077074/74266846-fc97e680-4d2a-11ea-8410-a43fabd611e9.jpg)

Is there a way we can have the bullet point centre-aligned with the first line of text? Also, is it me or the bullet point looks a non-standard small radius symbol?
